name: Bump version
on: [push]

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          github-token: ${{ secrets.github_token }}
          version-file: pyproject.toml
          version-path: tool.poetry.version
          skip-tag: true
          output-file: false
